# Use an official PHP image with Apache
FROM php:8.1-apache

# Copy the contents of your local project directory into the container's web directory
COPY src /var/www/html/


# Expose the Apache HTTP port
EXPOSE 80
